/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>
#include "customqlabel.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QWidget *widget;
    CustomQLabel *label_startup;
    QPushButton *btn_startup;
    QWidget *widget_2;
    QLabel *label_bimage;
    QPushButton *pushButton;
    QWidget *widget_3;
    QLabel *label_bimage3;
    QLabel *label_state1;
    QLabel *label_state2;
    QLabel *left_biage;
    QLabel *left_rail;
    QLabel *left_num_10;
    QLabel *left_num_1;
    QLabel *label_kmh;
    QLabel *right_biage;
    QLabel *right_rail;
    QLabel *label_energyback;
    QLabel *label_batterypic;
    QLabel *batterynum_10;
    QLabel *batterynum_1;
    QLabel *greenper;
    QLabel *time_h10;
    QLabel *time_h1;
    QLabel *time_dian;
    QLabel *time_m10;
    QLabel *time_m10_2;
    QLabel *pear_small;
    QLabel *trip_pic;
    QLabel *tripnum_10;
    QLabel *tripnum_1;
    QLabel *run_km;
    QLabel *odo_pic;
    QLabel *odonum_1;
    QLabel *odonum_2;
    QLabel *odonum_3;
    QLabel *run_km_2;
    QPushButton *wid3_return;
    QWidget *widget_4;
    QLabel *wid4_image;
    QLabel *wid4_rail;
    QLabel *wid4_leftarrow;
    QLabel *wid4_rightarrow;
    QLabel *wid4_speedpic;
    QLabel *wid4_speed10;
    QLabel *wid4_speed1;
    QLabel *wid4_kmhpic;
    QLabel *wid4_kmhpic_2;
    QLabel *wid4_bat1pic;
    QLabel *wid4_batadd;
    QLabel *wid4_bat1pic_2;
    QLabel *wid4_bit1_num10;
    QLabel *wid4_bit1_num1;
    QLabel *wid4_bit2_num1;
    QLabel *wid4_bit2_num10;
    QLabel *wid4_bit1_precent;
    QLabel *wid4_bit2_precent;
    QLabel *wid4_map;
    QLabel *wid4_faultpic;
    QLabel *wid4_faultdisp;
    QPushButton *wid4_return;
    QWidget *horizontalLayoutWidget;
    QHBoxLayout *boxlayout;
    QLabel *label;
    QLabel *start_gps;
    QLabel *label_2;
    QLabel *end_gps;
    QPushButton *gps_set;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1024, 600);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        widget = new QWidget(centralwidget);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setGeometry(QRect(0, 0, 1024, 600));
        label_startup = new CustomQLabel(widget);
        label_startup->setObjectName(QString::fromUtf8("label_startup"));
        label_startup->setGeometry(QRect(0, 0, 1024, 600));
        btn_startup = new QPushButton(widget);
        btn_startup->setObjectName(QString::fromUtf8("btn_startup"));
        btn_startup->setGeometry(QRect(870, 20, 131, 91));
        btn_startup->setStyleSheet(QString::fromUtf8("background:transparent;"));
        btn_startup->setFlat(true);
        widget_2 = new QWidget(centralwidget);
        widget_2->setObjectName(QString::fromUtf8("widget_2"));
        widget_2->setGeometry(QRect(0, 0, 1024, 600));
        label_bimage = new QLabel(widget_2);
        label_bimage->setObjectName(QString::fromUtf8("label_bimage"));
        label_bimage->setGeometry(QRect(0, 0, 1024, 600));
        label_bimage->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/audio/bimage.jpg\")"));
        pushButton = new QPushButton(widget_2);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(60, 130, 221, 61));
        pushButton->setStyleSheet(QString::fromUtf8("background:transparent;"));
        pushButton->setFlat(true);
        widget_3 = new QWidget(centralwidget);
        widget_3->setObjectName(QString::fromUtf8("widget_3"));
        widget_3->setGeometry(QRect(0, 0, 1024, 600));
        label_bimage3 = new QLabel(widget_3);
        label_bimage3->setObjectName(QString::fromUtf8("label_bimage3"));
        label_bimage3->setGeometry(QRect(0, 0, 1024, 600));
        label_bimage3->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/bimage.png\")"));
        label_state1 = new QLabel(widget_3);
        label_state1->setObjectName(QString::fromUtf8("label_state1"));
        label_state1->setGeometry(QRect(0, 0, 140, 96));
        label_state1->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/status_disp/signal.png\")"));
        label_state2 = new QLabel(widget_3);
        label_state2->setObjectName(QString::fromUtf8("label_state2"));
        label_state2->setGeometry(QRect(100, 0, 140, 96));
        label_state2->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/status_disp/location.png\")"));
        left_biage = new QLabel(widget_3);
        left_biage->setObjectName(QString::fromUtf8("left_biage"));
        left_biage->setGeometry(QRect(10, 130, 444, 420));
        left_biage->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/left_image.png\")"));
        left_rail = new QLabel(widget_3);
        left_rail->setObjectName(QString::fromUtf8("left_rail"));
        left_rail->setGeometry(QRect(10, 130, 444, 420));
        left_rail->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/left_rail/32.png\")"));
        left_num_10 = new QLabel(widget_3);
        left_num_10->setObjectName(QString::fromUtf8("left_num_10"));
        left_num_10->setGeometry(QRect(110, 260, 121, 151));
        left_num_10->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/speed_blue/3.png\")"));
        left_num_1 = new QLabel(widget_3);
        left_num_1->setObjectName(QString::fromUtf8("left_num_1"));
        left_num_1->setGeometry(QRect(230, 260, 121, 151));
        left_num_1->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/speed_blue/8.png\")"));
        label_kmh = new QLabel(widget_3);
        label_kmh->setObjectName(QString::fromUtf8("label_kmh"));
        label_kmh->setGeometry(QRect(205, 420, 53, 21));
        label_kmh->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/speed_blue/kmh.png\")"));
        right_biage = new QLabel(widget_3);
        right_biage->setObjectName(QString::fromUtf8("right_biage"));
        right_biage->setGeometry(QRect(560, 130, 444, 420));
        right_biage->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/right_image.png\")"));
        right_rail = new QLabel(widget_3);
        right_rail->setObjectName(QString::fromUtf8("right_rail"));
        right_rail->setGeometry(QRect(560, 130, 444, 420));
        right_rail->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/right_rail/46.png\")"));
        label_energyback = new QLabel(widget_3);
        label_energyback->setObjectName(QString::fromUtf8("label_energyback"));
        label_energyback->setGeometry(QRect(572, 258, 102, 245));
        label_energyback->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/energy_back/16.png\")"));
        label_batterypic = new QLabel(widget_3);
        label_batterypic->setObjectName(QString::fromUtf8("label_batterypic"));
        label_batterypic->setGeometry(QRect(760, 280, 41, 26));
        label_batterypic->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/batterypic/green3.png\")"));
        batterynum_10 = new QLabel(widget_3);
        batterynum_10->setObjectName(QString::fromUtf8("batterynum_10"));
        batterynum_10->setGeometry(QRect(710, 320, 66, 79));
        batterynum_10->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/batterynum/8.png\")"));
        batterynum_1 = new QLabel(widget_3);
        batterynum_1->setObjectName(QString::fromUtf8("batterynum_1"));
        batterynum_1->setGeometry(QRect(780, 320, 66, 79));
        batterynum_1->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/batterynum/8.png\")"));
        greenper = new QLabel(widget_3);
        greenper->setObjectName(QString::fromUtf8("greenper"));
        greenper->setGeometry(QRect(860, 360, 28, 25));
        greenper->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/batterynum/greenper.png\")"));
        time_h10 = new QLabel(widget_3);
        time_h10->setObjectName(QString::fromUtf8("time_h10"));
        time_h10->setGeometry(QRect(440, 190, 29, 35));
        time_h10->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/time/0.png\")"));
        time_h1 = new QLabel(widget_3);
        time_h1->setObjectName(QString::fromUtf8("time_h1"));
        time_h1->setGeometry(QRect(470, 190, 29, 35));
        time_h1->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/time/9.png\")"));
        time_dian = new QLabel(widget_3);
        time_dian->setObjectName(QString::fromUtf8("time_dian"));
        time_dian->setGeometry(QRect(495, 190, 29, 35));
        time_dian->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/time/maohao.png\")"));
        time_m10 = new QLabel(widget_3);
        time_m10->setObjectName(QString::fromUtf8("time_m10"));
        time_m10->setGeometry(QRect(520, 190, 29, 35));
        time_m10->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/time/2.png\")"));
        time_m10_2 = new QLabel(widget_3);
        time_m10_2->setObjectName(QString::fromUtf8("time_m10_2"));
        time_m10_2->setGeometry(QRect(550, 190, 29, 35));
        time_m10_2->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/time/5.png\")"));
        pear_small = new QLabel(widget_3);
        pear_small->setObjectName(QString::fromUtf8("pear_small"));
        pear_small->setGeometry(QRect(450, 220, 118, 147));
        pear_small->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/gear/xs.png\")"));
        trip_pic = new QLabel(widget_3);
        trip_pic->setObjectName(QString::fromUtf8("trip_pic"));
        trip_pic->setGeometry(QRect(480, 350, 64, 26));
        trip_pic->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/trip.png\")"));
        tripnum_10 = new QLabel(widget_3);
        tripnum_10->setObjectName(QString::fromUtf8("tripnum_10"));
        tripnum_10->setGeometry(QRect(465, 390, 28, 35));
        tripnum_10->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/tripnumber/1.png\")"));
        tripnum_1 = new QLabel(widget_3);
        tripnum_1->setObjectName(QString::fromUtf8("tripnum_1"));
        tripnum_1->setGeometry(QRect(490, 390, 28, 35));
        tripnum_1->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/tripnumber/7.png\")"));
        run_km = new QLabel(widget_3);
        run_km->setObjectName(QString::fromUtf8("run_km"));
        run_km->setGeometry(QRect(510, 400, 64, 26));
        run_km->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/tripnumber/km.png\")"));
        odo_pic = new QLabel(widget_3);
        odo_pic->setObjectName(QString::fromUtf8("odo_pic"));
        odo_pic->setGeometry(QRect(480, 470, 64, 26));
        odo_pic->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/odo.png\")"));
        odonum_1 = new QLabel(widget_3);
        odonum_1->setObjectName(QString::fromUtf8("odonum_1"));
        odonum_1->setGeometry(QRect(440, 510, 28, 35));
        odonum_1->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/tripnumber/1.png\")"));
        odonum_2 = new QLabel(widget_3);
        odonum_2->setObjectName(QString::fromUtf8("odonum_2"));
        odonum_2->setGeometry(QRect(465, 510, 28, 35));
        odonum_2->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/tripnumber/2.png\")"));
        odonum_3 = new QLabel(widget_3);
        odonum_3->setObjectName(QString::fromUtf8("odonum_3"));
        odonum_3->setGeometry(QRect(490, 510, 28, 35));
        odonum_3->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/tripnumber/3.png\")"));
        run_km_2 = new QLabel(widget_3);
        run_km_2->setObjectName(QString::fromUtf8("run_km_2"));
        run_km_2->setGeometry(QRect(510, 520, 64, 26));
        run_km_2->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/running/tripnumber/km.png\")"));
        wid3_return = new QPushButton(widget_3);
        wid3_return->setObjectName(QString::fromUtf8("wid3_return"));
        wid3_return->setGeometry(QRect(830, 40, 121, 51));
        wid3_return->setStyleSheet(QString::fromUtf8("background:transparent;"));
        wid3_return->setFlat(true);
        widget_4 = new QWidget(centralwidget);
        widget_4->setObjectName(QString::fromUtf8("widget_4"));
        widget_4->setGeometry(QRect(0, 0, 1024, 600));
        wid4_image = new QLabel(widget_4);
        wid4_image->setObjectName(QString::fromUtf8("wid4_image"));
        wid4_image->setGeometry(QRect(0, 0, 1024, 600));
        wid4_image->setStyleSheet(QString::fromUtf8("background-color: rgb(212, 212, 212);"));
        wid4_rail = new QLabel(widget_4);
        wid4_rail->setObjectName(QString::fromUtf8("wid4_rail"));
        wid4_rail->setGeometry(QRect(0, 0, 150, 600));
        wid4_rail->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/rail.png\")"));
        wid4_leftarrow = new QLabel(widget_4);
        wid4_leftarrow->setObjectName(QString::fromUtf8("wid4_leftarrow"));
        wid4_leftarrow->setGeometry(QRect(0, 20, 71, 67));
        wid4_leftarrow->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/leftlight_no.png\")"));
        wid4_rightarrow = new QLabel(widget_4);
        wid4_rightarrow->setObjectName(QString::fromUtf8("wid4_rightarrow"));
        wid4_rightarrow->setGeometry(QRect(72, 20, 71, 67));
        wid4_rightarrow->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/rightlight_yes.png\")"));
        wid4_speedpic = new QLabel(widget_4);
        wid4_speedpic->setObjectName(QString::fromUtf8("wid4_speedpic"));
        wid4_speedpic->setGeometry(QRect(20, 110, 94, 28));
        wid4_speedpic->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/speedpic.png\")"));
        wid4_speed10 = new QLabel(widget_4);
        wid4_speed10->setObjectName(QString::fromUtf8("wid4_speed10"));
        wid4_speed10->setGeometry(QRect(25, 150, 46, 57));
        wid4_speed10->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/speednum/5.png\")"));
        wid4_speed1 = new QLabel(widget_4);
        wid4_speed1->setObjectName(QString::fromUtf8("wid4_speed1"));
        wid4_speed1->setGeometry(QRect(70, 150, 46, 57));
        wid4_speed1->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/speednum/9.png\")"));
        wid4_kmhpic = new QLabel(widget_4);
        wid4_kmhpic->setObjectName(QString::fromUtf8("wid4_kmhpic"));
        wid4_kmhpic->setGeometry(QRect(20, 210, 94, 28));
        wid4_kmhpic->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/kmhpic.png\")"));
        wid4_kmhpic_2 = new QLabel(widget_4);
        wid4_kmhpic_2->setObjectName(QString::fromUtf8("wid4_kmhpic_2"));
        wid4_kmhpic_2->setGeometry(QRect(30, 540, 94, 28));
        wid4_kmhpic_2->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/readypic.png\")"));
        wid4_bat1pic = new QLabel(widget_4);
        wid4_bat1pic->setObjectName(QString::fromUtf8("wid4_bat1pic"));
        wid4_bat1pic->setGeometry(QRect(15, 280, 41, 26));
        wid4_bat1pic->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/batterypic/green2.png\")"));
        wid4_batadd = new QLabel(widget_4);
        wid4_batadd->setObjectName(QString::fromUtf8("wid4_batadd"));
        wid4_batadd->setGeometry(QRect(55, 280, 41, 26));
        wid4_batadd->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/batterypic/green5.png\")"));
        wid4_bat1pic_2 = new QLabel(widget_4);
        wid4_bat1pic_2->setObjectName(QString::fromUtf8("wid4_bat1pic_2"));
        wid4_bat1pic_2->setGeometry(QRect(95, 280, 41, 26));
        wid4_bat1pic_2->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/batterypic/green4.png\")"));
        wid4_bit1_num10 = new QLabel(widget_4);
        wid4_bit1_num10->setObjectName(QString::fromUtf8("wid4_bit1_num10"));
        wid4_bit1_num10->setGeometry(QRect(30, 320, 46, 57));
        wid4_bit1_num10->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/batterynum/6.png\")"));
        wid4_bit1_num1 = new QLabel(widget_4);
        wid4_bit1_num1->setObjectName(QString::fromUtf8("wid4_bit1_num1"));
        wid4_bit1_num1->setGeometry(QRect(70, 320, 46, 57));
        wid4_bit1_num1->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/batterynum/8.png\")"));
        wid4_bit2_num1 = new QLabel(widget_4);
        wid4_bit2_num1->setObjectName(QString::fromUtf8("wid4_bit2_num1"));
        wid4_bit2_num1->setGeometry(QRect(70, 430, 46, 57));
        wid4_bit2_num1->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/batterynum/8.png\")"));
        wid4_bit2_num10 = new QLabel(widget_4);
        wid4_bit2_num10->setObjectName(QString::fromUtf8("wid4_bit2_num10"));
        wid4_bit2_num10->setGeometry(QRect(30, 430, 46, 57));
        wid4_bit2_num10->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/batterynum/9.png\")"));
        wid4_bit1_precent = new QLabel(widget_4);
        wid4_bit1_precent->setObjectName(QString::fromUtf8("wid4_bit1_precent"));
        wid4_bit1_precent->setGeometry(QRect(50, 365, 46, 57));
        wid4_bit1_precent->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/batterynum/precent.png\")"));
        wid4_bit2_precent = new QLabel(widget_4);
        wid4_bit2_precent->setObjectName(QString::fromUtf8("wid4_bit2_precent"));
        wid4_bit2_precent->setGeometry(QRect(50, 475, 46, 57));
        wid4_bit2_precent->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/batterynum/precent.png\")"));
        wid4_map = new QLabel(widget_4);
        wid4_map->setObjectName(QString::fromUtf8("wid4_map"));
        wid4_map->setGeometry(QRect(150, 0, 874, 600));
        wid4_faultpic = new QLabel(widget_4);
        wid4_faultpic->setObjectName(QString::fromUtf8("wid4_faultpic"));
        wid4_faultpic->setGeometry(QRect(770, 0, 215, 127));
        wid4_faultpic->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/fault_pic.png\")"));
        wid4_faultdisp = new QLabel(widget_4);
        wid4_faultdisp->setObjectName(QString::fromUtf8("wid4_faultdisp"));
        wid4_faultdisp->setGeometry(QRect(800, 0, 151, 114));
        wid4_faultdisp->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/motorfault.png\")"));
        wid4_return = new QPushButton(widget_4);
        wid4_return->setObjectName(QString::fromUtf8("wid4_return"));
        wid4_return->setGeometry(QRect(790, 500, 230, 94));
        wid4_return->setStyleSheet(QString::fromUtf8("background-image:url(\"./pic/navigation/return.png\")\n"
""));
        wid4_return->setFlat(true);
        horizontalLayoutWidget = new QWidget(widget_4);
        horizontalLayoutWidget->setObjectName(QString::fromUtf8("horizontalLayoutWidget"));
        horizontalLayoutWidget->setGeometry(QRect(149, -1, 881, 601));
        boxlayout = new QHBoxLayout(horizontalLayoutWidget);
        boxlayout->setObjectName(QString::fromUtf8("boxlayout"));
        boxlayout->setContentsMargins(0, 0, 0, 0);
        label = new QLabel(widget_4);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(760, 20, 61, 31));
        QFont font;
        font.setPointSize(14);
        label->setFont(font);
        label->setStyleSheet(QString::fromUtf8("background-color: rgb(186, 189, 182);"));
        start_gps = new QLabel(widget_4);
        start_gps->setObjectName(QString::fromUtf8("start_gps"));
        start_gps->setGeometry(QRect(820, 20, 191, 31));
        QFont font1;
        font1.setPointSize(13);
        start_gps->setFont(font1);
        start_gps->setStyleSheet(QString::fromUtf8("background-color: rgb(186, 189, 182);"));
        label_2 = new QLabel(widget_4);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(760, 60, 61, 31));
        label_2->setFont(font);
        label_2->setStyleSheet(QString::fromUtf8("background-color: rgb(186, 189, 182);"));
        end_gps = new QLabel(widget_4);
        end_gps->setObjectName(QString::fromUtf8("end_gps"));
        end_gps->setGeometry(QRect(820, 60, 191, 31));
        end_gps->setFont(font1);
        end_gps->setStyleSheet(QString::fromUtf8("background-color: rgb(186, 189, 182);"));
        gps_set = new QPushButton(widget_4);
        gps_set->setObjectName(QString::fromUtf8("gps_set"));
        gps_set->setGeometry(QRect(890, 100, 101, 41));
        gps_set->setFont(font1);
        wid4_image->raise();
        wid4_rail->raise();
        wid4_leftarrow->raise();
        wid4_rightarrow->raise();
        wid4_speedpic->raise();
        wid4_speed10->raise();
        wid4_speed1->raise();
        wid4_kmhpic->raise();
        wid4_kmhpic_2->raise();
        wid4_bat1pic->raise();
        wid4_batadd->raise();
        wid4_bat1pic_2->raise();
        wid4_bit1_num10->raise();
        wid4_bit1_num1->raise();
        wid4_bit2_num1->raise();
        wid4_bit2_num10->raise();
        wid4_bit1_precent->raise();
        wid4_bit2_precent->raise();
        wid4_map->raise();
        horizontalLayoutWidget->raise();
        wid4_return->raise();
        wid4_faultdisp->raise();
        wid4_faultpic->raise();
        label->raise();
        start_gps->raise();
        label_2->raise();
        end_gps->raise();
        gps_set->raise();
        MainWindow->setCentralWidget(centralwidget);
        widget_2->raise();
        widget_3->raise();
        widget->raise();
        widget_4->raise();

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        label_startup->setText(QString());
        btn_startup->setText(QString());
        label_bimage->setText(QString());
        pushButton->setText(QString());
        label_bimage3->setText(QString());
        label_state1->setText(QString());
        label_state2->setText(QString());
        left_biage->setText(QString());
        left_rail->setText(QString());
        left_num_10->setText(QString());
        left_num_1->setText(QString());
        label_kmh->setText(QString());
        right_biage->setText(QString());
        right_rail->setText(QString());
        label_energyback->setText(QString());
        label_batterypic->setText(QString());
        batterynum_10->setText(QString());
        batterynum_1->setText(QString());
        greenper->setText(QString());
        time_h10->setText(QString());
        time_h1->setText(QString());
        time_dian->setText(QString());
        time_m10->setText(QString());
        time_m10_2->setText(QString());
        pear_small->setText(QString());
        trip_pic->setText(QString());
        tripnum_10->setText(QString());
        tripnum_1->setText(QString());
        run_km->setText(QString());
        odo_pic->setText(QString());
        odonum_1->setText(QString());
        odonum_2->setText(QString());
        odonum_3->setText(QString());
        run_km_2->setText(QString());
        wid3_return->setText(QString());
        wid4_image->setText(QString());
        wid4_rail->setText(QString());
        wid4_leftarrow->setText(QString());
        wid4_rightarrow->setText(QString());
        wid4_speedpic->setText(QString());
        wid4_speed10->setText(QString());
        wid4_speed1->setText(QString());
        wid4_kmhpic->setText(QString());
        wid4_kmhpic_2->setText(QString());
        wid4_bat1pic->setText(QString());
        wid4_batadd->setText(QString());
        wid4_bat1pic_2->setText(QString());
        wid4_bit1_num10->setText(QString());
        wid4_bit1_num1->setText(QString());
        wid4_bit2_num1->setText(QString());
        wid4_bit2_num10->setText(QString());
        wid4_bit1_precent->setText(QString());
        wid4_bit2_precent->setText(QString());
        wid4_map->setText(QString());
        wid4_faultpic->setText(QString());
        wid4_faultdisp->setText(QString());
        wid4_return->setText(QString());
        label->setText(QApplication::translate("MainWindow", "\350\265\267\347\202\271:", nullptr));
        start_gps->setText(QString());
        label_2->setText(QApplication::translate("MainWindow", "\347\273\210\347\202\271:", nullptr));
        end_gps->setText(QString());
        gps_set->setText(QApplication::translate("MainWindow", "\350\256\276\347\275\256\350\267\257\347\272\277", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
